# Generated by Django 3.2.9 on 2022-08-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20220207_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('C', 'Cultural'), ('S', 'Sports')], max_length=1, verbose_name='Category'),
        ),
    ]
