# Generated by Django 3.2.9 on 2023-01-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_rules',
            field=models.TextField(default='null', verbose_name='Event Rules'),
        ),
        migrations.AlterField(
            model_name='event',
            name='entry_fee',
            field=models.IntegerField(default=0, verbose_name='Entry Fee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prize_money',
            field=models.TextField(default=0, verbose_name='Prize Money JSON'),
        ),
    ]
