# Generated by Django 3.2.9 on 2023-03-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20230122_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('C', 'Cultural'), ('T', 'Technical'), ('S', 'Sports')], max_length=1, verbose_name='Category'),
        ),
    ]
