# Generated by Django 3.2.9 on 2023-03-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='criteria',
            field=models.TextField(default='{"C": 1, "T": 2, "S": 0}', verbose_name='Criteria JSON (DONT FILL THIS)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_filled_profile',
            field=models.BooleanField(default=True, verbose_name='Has Filled Profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_phone_no_verified',
            field=models.BooleanField(default=True, verbose_name='Is Phone Number Verified'),
        ),
    ]
